#!/bin/bash
set +o noclobber

infiles=$1
factor=$2

for i in ${infiles}; do
    [ -e "$i" ] || continue
    awk -v f="$factor" '{c=$2; l=$3; u=$4; new_l = c - f*(c-l); new_u = c + f*(u-c); print $1, c, (new_l>0?new_l:0), (new_u>0?new_u:0)}' "$i" > "${i}.tmp"
    mv "${i}.tmp" "$i"
done
