#!/bin/bash
set +o noclobber

rm -rf allcres.dat


for f in res/cres*; do 
    if [ "$(awk 'NR==1{print ($7=="")}' "$f")" -eq 1 ]; then
        continue    # Skip if 7th column is empty in first line
    else
        #awk 'NF>=7{print $1, $2, $3, $4, $5, $7, $8}' "$f"
        awk 'NF>=7{print $1, $6, $2, $3, $4, $5, $7, $8}' "$f"
    fi
done > allcres.dat
