#!/bin/bash

current_dir=$(pwd)
mkdir -p "${current_dir}/mods/vlookdir"
rm -f "${current_dir}/mods/vlookdir" 2> /dev/null
for dir in ${current_dir}/mods/m*/; do
    if [[ -f "${dir}pgplot.ps" ]]; then
        dname=$(basename "$dir")
        cp "${dir}pgplot.ps" "${current_dir}/mods/vlookdir/${dname}.ps"
    fi
done
