#!/bin/bash
set +o noclobber

# Get the current directory where the script is being run
current_dir=$(pwd)

# Parameters passed to the script
file=$1
output=$2
spectrograph=$3

# Set wavemin and step based on the spectrograph
case $spectrograph in
    muse)
        wavemin=4750
        step=1.25
        ;;
    stis)
        wavemin=8275.0
        step=0.55859375
        ;;
    *)
        echo "Invalid spectrograph. Please enter 'muse' or 'stis'."
        exit 1
        ;;
esac


# Define other inputs for the imfit command
poly_order=10
cutoff=0
num_peaks=60
smooth=0

# Remove any existing 'out' file
rm -f out

# Source the SCO environment configuration if not already sourced
if [ -z "$SCO_FRAMEWORK_BIN" ]; then
    script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
    source "${script_dir}/sco_env.sh"
fi

# Run the imfit application
"${SCO_FRAMEWORK_BIN}/imfit" << eof
$file
$poly_order
$cutoff
$num_peaks
$smooth
/vcps
-1
eof

# Process the 'out' file and create the final output file
awk -v wavemin=$wavemin -v step=$step '{print wavemin + step * ($1 - 1), $2, $3}' out | grep -v NaN > $output

name=$(basename "${file}" .spec)

# Rename the plot file
if [ -f pgplot.ps ]; then
   mv pgplot.ps ${name}_rimfit.ps
fi
