#!/bin/bash

# Parameters
input_file=$1
wavefitmin=$2
wavefitmax=$3
redshift=$4
velocity=100.0 # Initial guess: velocity can be customized if required later
spectrograph=$5
smoothing=$6
rms=$7

# rmcfit bin0105sp 8275.0 8847.0 0.001556 stis 2.0 5.31209335E-02

# Set wavemin and step based on the spectrograph
case $spectrograph in
    muse)
        wavemin=4750.0
        step=1.25
        ;;
    stis)
        wavemin=8275.0
        step=0.55859375
        ;;
    *)
        echo "Invalid spectrograph. Please enter 'muse' or 'stis'."
        exit 1
        ;;
esac

# Source the SCO environment configuration if not already sourced
if [ -z "$SCO_FRAMEWORK_BIN" ]; then
    script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
    source "${script_dir}/sco_env.sh"
fi

"${SCO_FRAMEWORK_BIN}/mcfitw" << eof
${input_file}.norm
${input_file}
${wavemin} ${step}
0 0
Tlist
${wavemin} ${step}
0 0
${wavefitmin} ${wavefitmax}
${redshift} ${velocity}
${smoothing}
2e-5
0
${rms}
0
100
$1mc
/null
eof

rm -f *.def
